apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: spring-k8s-demo
  newName: jhjun07/spring-k8s-demo
  newTag: 4755c72e2e8495cf4b32928bc7426b4a85fb64ff
