apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: jhjun07/spring-k8s-demo:ca20ec29ab220b38f1d03d7bef34630a16590b26
          ports:
            - containerPort: 8080
          imagePullPolicy: Always