apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: spring-app
  ports:
    - name: http
      port: 8080       # 클러스터 내부에서 접근할 포트
      targetPort: 8080 # 컨테이너 포트