apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev

resources:
  - ../../base

images:
  - name: spring-k8s-demo
    newName: jhjun07/spring-k8s-demo
    newTag: 435448e9222239c043f153e088eaf4899253ab59

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
