apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev

resources:
  - ../../base

images:
  - name: spring-k8s-demo
    newName: jhjun07/spring-k8s-demo
    newTag: 216edec46249a6ef69485e37119ddcf7bf8936c8

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
