apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev

resources:
  - ../../base

images:
  - name: spring-k8s-demo
    newName: jhjun07/spring-k8s-demo
    newTag: 3d26f4a953af908fe19ef03144181a3a4b3b2e9f

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
